name: 'Expose whut'
on: 'workflow_dispatch'
jobs:
  expose_secret:
    name: 'Expose this secret'
    runs-on: 'ubuntu-latest'
    steps:
      - name: My first action
        env:
          PASSWORD: ${{ secrets.WIFI_PASSWORD }}https://github.com/aaa-te-st/test-actions
        run: echo "Check this password:" + ${{ $PASSWORD }}
